[package]
name = "orders-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.55", features = ["derive"] }
comfy-table = "7.2.2"
csv = "1.4.0"
rand = "0.9"
strum = "0.27.2"
strum_macros = "0.27.2"

[profile.profiling]
inherits = "release"
debug = true
split-debuginfo = "packed"
